In [1]:
import numpy as np
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8], [10, 11, 12]])
mat1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  8],
       [10, 11, 12]])

In [2]:
mat2 = np.array([[2, 1, 4], [4, 1, 7], [4, 2, 9], [5, 21, 1]])
mat2

array([[ 2,  1,  4],
       [ 4,  1,  7],
       [ 4,  2,  9],
       [ 5, 21,  1]])

In [3]:
mat1.shape

(4, 3)

In [4]:
mat2.shape

(4, 3)

In [5]:
mat1.dot(mat2.T)

array([[ 16,  27,  35,  50],
       [ 37,  63,  80, 131],
       [ 54,  92, 116, 211],
       [ 79, 135, 170, 293]])

In [7]:
mat1.T.dot(mat2)

array([[ 96, 229, 105],
       [111, 254, 126],
       [122, 277, 138]])

In [8]:
np.reshape(mat1, [3, 4]).dot(mat2)

array([[ 42,  93,  49],
       [102, 193, 133],
       [160, 292, 213]])